### ISSUE TITLE
401에 대해서 로그인 화면으로 이동하는 공통로직 구현

### ISSUE THREAD

**Issue by rhkrwngud445** [WithPeace/with-peace-android#38]
### 기능 설명
[공통로직]
Interceptor에서 흘려온 401에 대해서 로그인 화면으로 이동하게 처리한다.

### 개발 일정

~03/05

### 자식 이슈

X

### 부가 설명

X

**Comment by rhkrwngud445** [comment]
생각하는 로직
- Domain Layer에 Response에 NoAuth 타입 추가 Failure 상속타입으로 포함시켜도 좋을듯
- BaseViewModel에서 NoAuth에 대한 상태관리

Reference
- https://medium.com/@aykhanvaliyev/navigation-with-viewmodel-when-jetpack-compose-is-the-actor-af56539935b7

**Comment by chws0508** [comment]
> 생각하는 로직
> 
> * Domain Layer에 Response에 NoAuth 타입 추가 Failure 상속타입으로 포함시켜도 좋을듯
> * BaseViewModel에서 NoAuth에 대한 상태관리
> 
> Reference
> 
> * https://medium.com/@aykhanvaliyev/navigation-with-viewmodel-when-jetpack-compose-is-the-actor-af56539935b7

아주 좋아요!! UnAuthroized 네이밍은 어떤가요??

**Comment by rhkrwngud445** [comment]
UnAuthorized 좋습니다!
