### ISSUE TITLE
특정 모바일 기기에서 이미지 폴더를 가져오지 못하는 버그

### ISSUE THREAD

**Issue by chws0508** [WithPeace/with-peace-android#62]
### 버그 설명

특정 기기에서 이미지 폴더를 가져오는 부분에서 nullPointExceptiond이 나는 문제

### 예상 동작

정상적으로 폴더 리스트를 가져온다

### 실제 동작

nullPointerException이 발생한다

### 스크린샷 첨부

![스크린샷 2024-03-20 오후 2 28 34](https://github.com/WithPeace/with-peace-android/assets/76036731/6e1fd2bd-3d67-4701-bd87-f75eb71ec0b4)

### 환경

갤럭시21+ 안드로이드 14

**Comment by rhkrwngud445** [comment]
hoxy? 
https://jm-son.tistory.com/10

**Comment by chws0508** [comment]
해결완료... 폴더가 없는 이미지가 있어서 임시로 폴더가 없는 경우는 일단 넘김... 추후 폴더가 없는경우 임의로 unknown 폴더 만들어줄 예정
