### ISSUE TITLE
refresh 갱신이 안되는 이슈

### ISSUE THREAD

**Issue by rhkrwngud445** [WithPeace/with-peace-android#68]
### 버그 설명
리프레시 갱신이 안되는듯 합니다. 확인 중

### 예상 동작
작동 되어야겠지?

### 실제 동작

토큰 갱신 되어야겠지?

### 스크린샷 첨부
<img width="974" alt="스크린샷 2024-03-26 오전 12 00 51" src="https://github.com/WithPeace/with-peace-android/assets/33768873/dfcf1182-0aac-43ca-aa4d-6af916badac6">

### 환경
33 API nexus7 emulator

**Comment by chws0508** [comment]
저도 이 이슈를 겪고 있습니다

**Comment by rhkrwngud445** [comment]
최초 로그인 작업 후 Interceptor 봐볼게요~

**Comment by rhkrwngud445** [comment]
interceptor에서 Refresh API 호출시 refresh 토큰을 안넣어주는 것 같네요!
