### ISSUE TITLE
최초 로그인을 안하고 화면을 나갈시, google id token에 인해 자동 로그인이 되는 버그

### ISSUE THREAD

**Issue by rhkrwngud445** [WithPeace/with-peace-android#73]
### 버그 설명

토큰이 로컬에 저장되어 자동로그인으로 구분됨

### 예상 동작

구글 토큰이 있어도 login이 되어선 안된다.

### 실제 동작

자동 로그인 됨

### 비고

signUp 화면에서 앱을 종료할 때는 토큰제거..?

**Comment by chws0508** [comment]
로그인 할 시, Role을 주는것으로 바뀌었기 때문에, Role이 Guest면 회원가입으로, User면 홈화면으로 이동시키는 로직이 추가되면 될 것 같습니다. 또한 회원가입에 성공하면, Role을 User로 업데이트 시켜주면 될 것 같습니다.

**Comment by rhkrwngud445** [comment]
좋은 방식 같습니다! 해당 방식으로 진행하고 추후 자동로그인으로 마이그레이션 하면 될 것 같네요!
